version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=root:password@tcp(db:3306)/locations?parseTime=true

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=locations
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: